### ISSUE TITLE
Sort packages case insensitively

### ISSUE THREAD

**Issue by miyagawa** [AndyA/CPAN--Mini--Inject#23]
It seems CPAN::Mini::Inject generates 02packages by sorting the package name case sensitively (using perl's built-in sort). https://metacpan.org/source/MITHALDU/CPAN-Mini-Inject-0.33/lib/CPAN/Mini/Inject.pm#L446

PAUSE does it case insensitively, and CPAN::Mini::Inject should do it the same.
https://github.com/andk/pause/blob/master/lib/PAUSE/mldistwatch.pm#L635

**Comment by wchristian** [comment]
Should be fixed by #24, please let me know if there's more problems! :)
