### ISSUE TITLE
Add Regexp::IPv6 as test dependency

### ISSUE THREAD

**Issue by XSven** [AndyA/CPAN--Mini--Inject#27]
please consider the important RT issue [unable to contact the remote mirror (without Regexp::IPv6?)](https://rt.cpan.org/Public/Bug/Display.html?id=144685)

**Comment by briandfoy** [comment]
This is already #26, but I'll apply the change.

**Comment by briandfoy** [comment]
I've merged #26 in briandfoy/cpan-mini-inject in 93b6cef88c9269033d5592e360ed1841d438fff3. I can't close this issue, but look to the new repo for future work.
